"""Onboarding service + participant registry for the MVD compose dataspace.

Serves a small web UI to create/manage companies and a JSON API that acts as
the dataspace participant registry. Deployment happens via `podman compose`
(same mechanism as new-company.ps1); on a Portainer host the deploy backend
would be swapped for the Portainer API.

No external dependencies - Python stdlib only.

    python server.py [port]     # default 5175
"""
import json
import re
import shutil
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

ROOT = Path(__file__).parent                      # compose/onboarding
COMPOSE_ROOT = ROOT.parent                        # compose/
COMPANIES_DIR = COMPOSE_ROOT / "companies"
TRAEFIK_DYNAMIC = COMPOSE_ROOT / "infra" / "config" / "traefik" / "dynamic"
COMPANY_COMPOSE = COMPOSE_ROOT / "company" / "docker-compose.yml"

NAME_RE = re.compile(r"^[a-z][a-z0-9-]{1,30}$")
RESERVED_NAMES = {"infra", "vault", "postgres", "keycloak", "traefik", "issuerservice"}
API_KEY = "password"
TRAEFIK_HOST = "127.0.0.1"
TRAEFIK_PORT = 80

# name -> {"state": "deploying"|"seeding"|"ready"|"failed", "log": [str], "startedAt": iso}
jobs = {}
jobs_lock = threading.Lock()


def log_job(name, message):
    with jobs_lock:
        job = jobs.setdefault(name, {"state": "deploying", "log": []})
        job["log"].append(f"{datetime.now().strftime('%H:%M:%S')}  {message}")


def set_job_state(name, state):
    with jobs_lock:
        jobs.setdefault(name, {"log": []})["state"] = state


# ---------------------------------------------------------------- generation

def env_file_content(name, demo_assets):
    return f"COMPANY={name}\nSEED_DEMO_ASSETS={'true' if demo_assets else 'false'}\n"


def traefik_route_content(name):
    return f"""# Traefik routes for company '{name}' (generated by onboarding service)
http:
  routers:
    cp-{name}:
      rule: "Host(`cp.{name}.localhost`)"
      entryPoints: [web]
      service: cp-{name}

    dp-{name}:
      rule: "Host(`dp.{name}.localhost`) && PathPrefix(`/public`)"
      entryPoints: [web]
      middlewares: [strip-public-{name}]
      service: dp-{name}

    ih-cs-{name}:
      rule: "Host(`ih.{name}.localhost`) && PathPrefix(`/cs`)"
      entryPoints: [web]
      middlewares: [strip-cs-{name}]
      service: ih-identity-{name}

    ih-did-{name}:
      rule: "Host(`ih.{name}.localhost`)"
      entryPoints: [web]
      service: ih-did-{name}

  middlewares:
    strip-public-{name}:
      stripPrefix:
        prefixes: ["/public"]
    strip-cs-{name}:
      stripPrefix:
        prefixes: ["/cs"]

  services:
    cp-{name}:
      loadBalancer:
        servers:
          - url: "http://controlplane-{name}:8081"
    dp-{name}:
      loadBalancer:
        servers:
          - url: "http://dataplane-{name}:11002"
    ih-identity-{name}:
      loadBalancer:
        servers:
          - url: "http://identityhub-{name}:7081"
    ih-did-{name}:
      loadBalancer:
        servers:
          - url: "http://identityhub-{name}:7083"
"""


def company_metadata(name):
    meta_file = COMPANIES_DIR / name / "company.json"
    if meta_file.exists():
        try:
            return json.loads(meta_file.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return {}


def create_company_files(name, display_name, description, demo_assets):
    company_dir = COMPANIES_DIR / name
    company_dir.mkdir(parents=True, exist_ok=True)
    (company_dir / "storage" / "assets").mkdir(parents=True, exist_ok=True)
    (company_dir / "storage" / "downloads").mkdir(parents=True, exist_ok=True)
    (company_dir / ".env").write_text(env_file_content(name, demo_assets), encoding="ascii")
    (company_dir / "company.json").write_text(json.dumps({
        "name": name,
        "displayName": display_name or name,
        "description": description or "",
        "demoAssets": bool(demo_assets),
        "createdAt": datetime.now(timezone.utc).isoformat(),
    }, indent=2), encoding="utf-8")
    (TRAEFIK_DYNAMIC / f"company-{name}.yml").write_text(traefik_route_content(name), encoding="ascii")


# ------------------------------------------------------------------- podman

def run_podman(args, timeout=180):
    result = subprocess.run(
        ["podman"] + args,
        capture_output=True, text=True, errors="replace", timeout=timeout,
    )
    return result


def podman_ps():
    """Returns {container_name: {"state": ..., "exitCode": ..., "exited": ...}}"""
    result = run_podman(["ps", "-a", "--format", "json"], timeout=30)
    if result.returncode != 0:
        return {}
    try:
        rows = json.loads(result.stdout or "[]")
    except json.JSONDecodeError:
        return {}
    out = {}
    for row in rows:
        for cname in row.get("Names") or []:
            out[cname] = {
                "state": row.get("State", "unknown"),
                "exitCode": row.get("ExitCode"),
                "exited": row.get("Exited", False),
            }
    return out


def compose_up(name):
    env_file = COMPANIES_DIR / name / ".env"
    return run_podman([
        "compose", "-p", f"mvd-{name}",
        "--env-file", str(env_file),
        "-f", str(COMPANY_COMPOSE),
        "up", "-d",
    ], timeout=420)


def compose_down(name):
    env_file = COMPANIES_DIR / name / ".env"
    return run_podman([
        "compose", "-p", f"mvd-{name}",
        "--env-file", str(env_file),
        "-f", str(COMPANY_COMPOSE),
        "down",
    ], timeout=180)


def restart_traefik():
    """Windows bind mounts do not deliver file-watch events into the container,
    so Traefik must be restarted to pick up new/removed dynamic route files."""
    return run_podman(["restart", "traefik"], timeout=60)


# -------------------------------------------------------------- deploy jobs

def deploy_company(name):
    try:
        log_job(name, "Lade Traefik-Routen neu...")
        set_job_state(name, "deploying")
        restart_traefik()
        log_job(name, "Deploye Stack (podman compose up)...")
        result = compose_up(name)
        if result.returncode != 0:
            log_job(name, f"FEHLER beim Deploy: {result.stderr[-500:]}")
            set_job_state(name, "failed")
            return
        log_job(name, "Stack gestartet. Warte auf Seeds (Identität, Credentials, Assets)...")
        set_job_state(name, "seeding")

        deadline = time.time() + 420
        seeds = [f"seed-identity-{name}", f"seed-controlplane-{name}"]
        while time.time() < deadline:
            ps = podman_ps()
            states = {s: ps.get(s) for s in seeds}
            failed = [s for s, st in states.items()
                      if st and st["state"] == "exited" and st.get("exitCode") not in (0, None)]
            if failed:
                for s in failed:
                    log_job(name, f"FEHLER: {s} beendet mit Exit-Code {states[s].get('exitCode')}")
                set_job_state(name, "failed")
                return
            done = all(st and st["state"] == "exited" and st.get("exitCode") == 0
                       for st in states.values())
            if done:
                log_job(name, "Seeds abgeschlossen - Credentials ausgestellt, Assets angelegt.")
                log_job(name, f"Unternehmen '{name}' ist voll teilnahmefähig.")
                set_job_state(name, "ready")
                return
            time.sleep(5)
        log_job(name, "TIMEOUT: Seeds nicht innerhalb von 7 Minuten fertig.")
        set_job_state(name, "failed")
    except Exception as exc:  # noqa: BLE001 - job must never crash the server
        log_job(name, f"FEHLER: {exc}")
        set_job_state(name, "failed")


# ------------------------------------------------------------------- status

def mgmt_probe(name):
    """Asks the company's management API for its assets. Returns count or None."""
    body = json.dumps({
        "@context": ["https://w3id.org/edc/connector/management/v2"],
        "@type": "QuerySpec",
    }).encode("utf-8")
    req = urllib.request.Request(
        f"http://{TRAEFIK_HOST}:{TRAEFIK_PORT}/api/mgmt/v4/assets/request",
        data=body, method="POST",
        headers={
            "Host": f"cp.{name}.localhost",
            "Content-Type": "application/json",
            "X-Api-Key": API_KEY,
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=4) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            return len(data) if isinstance(data, list) else None
    except (urllib.error.URLError, json.JSONDecodeError, TimeoutError, OSError):
        return None


def company_status(name, ps):
    def cstate(prefix):
        st = ps.get(f"{prefix}-{name}")
        return st["state"] if st else "missing"

    def seed_ok(prefix):
        st = ps.get(f"{prefix}-{name}")
        if not st:
            return None
        return st["state"] == "exited" and st.get("exitCode") == 0

    meta = company_metadata(name)
    with jobs_lock:
        job = jobs.get(name)
        job_info = {"state": job["state"], "log": job["log"][-20:]} if job else None

    running = all(cstate(p) == "running" for p in ("cp", "dp", "ih"))
    assets = mgmt_probe(name) if cstate("cp") == "running" else None
    return {
        "name": name,
        "displayName": meta.get("displayName", name),
        "description": meta.get("description", ""),
        "demoAssets": meta.get("demoAssets", False),
        "createdAt": meta.get("createdAt"),
        "did": f"did:web:identityhub-{name}%3A7083:{name}",
        "dspEndpoint": f"http://controlplane-{name}:8082/api/dsp/2025-1",
        "managementUrl": f"http://cp.{name}.localhost/api/mgmt",
        "dataplanePublicUrl": f"http://dp.{name}.localhost/public/api/public",
        "containers": {
            "controlplane": cstate("cp"),
            "dataplane": cstate("dp"),
            "identityhub": cstate("ih"),
        },
        "seeds": {
            "identity": seed_ok("seed-identity"),
            "controlplane": seed_ok("seed-controlplane"),
        },
        "assetCount": assets,
        "healthy": running and assets is not None,
        "job": job_info,
    }


def list_companies():
    if not COMPANIES_DIR.exists():
        return []
    names = sorted(d.name for d in COMPANIES_DIR.iterdir() if (d / ".env").exists())
    ps = podman_ps()
    return [company_status(n, ps) for n in names]


def delete_company(name):
    log_job(name, "Stoppe und entferne Stack...")
    compose_down(name)
    route = TRAEFIK_DYNAMIC / f"company-{name}.yml"
    if route.exists():
        route.unlink()
    company_dir = COMPANIES_DIR / name
    if company_dir.exists():
        shutil.rmtree(company_dir)
    restart_traefik()
    with jobs_lock:
        jobs.pop(name, None)


# --------------------------------------------------------------------- http

class Handler(BaseHTTPRequestHandler):
    def send_json(self, status, data):
        raw = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def send_file(self, filename, content_type):
        path = ROOT / filename
        if not path.exists():
            self.send_json(404, {"error": "not found"})
            return
        raw = path.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def read_body(self):
        length = int(self.headers.get("Content-Length") or 0)
        if not length:
            return {}
        return json.loads(self.rfile.read(length).decode("utf-8"))

    def do_GET(self):
        if self.path in ("/", "/index.html"):
            self.send_file("index.html", "text/html; charset=utf-8")
        elif self.path == "/app.js":
            self.send_file("app.js", "application/javascript; charset=utf-8")
        elif self.path == "/styles.css":
            self.send_file("styles.css", "text/css; charset=utf-8")
        elif self.path == "/api/companies":
            self.send_json(200, {"companies": list_companies()})
        else:
            self.send_json(404, {"error": "not found"})

    def do_POST(self):
        try:
            if self.path == "/api/companies":
                body = self.read_body()
                name = (body.get("name") or "").strip().lower()
                if not NAME_RE.match(name):
                    self.send_json(400, {"error": "Name muss klein geschrieben sein, mit Buchstabe beginnen, nur a-z 0-9 und '-' (max 31 Zeichen)."})
                    return
                if name in RESERVED_NAMES:
                    self.send_json(400, {"error": f"'{name}' ist ein reservierter Name."})
                    return
                if (COMPANIES_DIR / name).exists():
                    self.send_json(409, {"error": f"Unternehmen '{name}' existiert bereits."})
                    return
                create_company_files(name, body.get("displayName"), body.get("description"),
                                     bool(body.get("demoAssets")))
                log_job(name, f"Unternehmen '{name}' angelegt (env, Traefik-Route, Metadaten).")
                threading.Thread(target=deploy_company, args=(name,), daemon=True).start()
                self.send_json(202, {"status": "deploying", "name": name})
            elif re.match(r"^/api/companies/[a-z0-9-]+/redeploy$", self.path):
                name = self.path.split("/")[3]
                if not (COMPANIES_DIR / name).exists():
                    self.send_json(404, {"error": "unbekanntes Unternehmen"})
                    return
                log_job(name, "Redeploy angefordert...")
                threading.Thread(target=deploy_company, args=(name,), daemon=True).start()
                self.send_json(202, {"status": "deploying", "name": name})
            else:
                self.send_json(404, {"error": "not found"})
        except Exception as exc:  # noqa: BLE001
            self.send_json(500, {"error": str(exc)})

    def do_DELETE(self):
        try:
            m = re.match(r"^/api/companies/([a-z0-9-]+)$", self.path)
            if not m:
                self.send_json(404, {"error": "not found"})
                return
            name = m.group(1)
            if not (COMPANIES_DIR / name).exists():
                self.send_json(404, {"error": "unbekanntes Unternehmen"})
                return
            delete_company(name)
            self.send_json(200, {"status": "deleted", "name": name,
                                 "note": "Datenbanken und Vault-Secrets bleiben erhalten."})
        except Exception as exc:  # noqa: BLE001
            self.send_json(500, {"error": str(exc)})

    def log_message(self, fmt, *args):  # quieter console
        if "/api/companies" not in (args[0] if args else ""):
            super().log_message(fmt, *args)


def main():
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 5175
    server = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    print(f"Onboarding service on http://127.0.0.1:{port}")
    print("Requires the infra stack to be running (Traefik on port 80).")
    server.serve_forever()


if __name__ == "__main__":
    main()
