apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-photo-api
  namespace: provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-photo-api
  template:
    metadata:
      labels:
        app: custom-photo-api
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: custom-photo
              mountPath: /usr/share/nginx/html
      volumes:
        - name: custom-photo
          configMap:
            name: custom-photo
---
apiVersion: v1
kind: Service
metadata:
  name: custom-photo-api
  namespace: provider
spec:
  selector:
    app: custom-photo-api
  ports:
    - port: 80
      targetPort: 80