# Creates a new dataspace participant ("Unternehmen") from the company template:
#  - writes compose/companies/<name>/.env
#  - writes the Traefik route file compose/infra/config/traefik/dynamic/company-<name>.yml
#  - deploys the stack (unless -NoDeploy is given)
#
# Usage:
#   .\new-company.ps1 -Name mueller-gmbh
#   .\new-company.ps1 -Name provider -DemoAssets   # additionally seeds asset-1/2/3
param(
    [Parameter(Mandatory = $true)]
    [string]$Name,
    [switch]$DemoAssets,
    [switch]$NoDeploy
)

$ErrorActionPreference = "Stop"

if ($Name -cnotmatch '^[a-z][a-z0-9-]{1,30}$') {
    Write-Error "Company name must be lowercase, start with a letter and contain only a-z, 0-9 and '-' (max 31 chars). Got: '$Name'"
}

$composeRoot = $PSScriptRoot
$companyDir = Join-Path $composeRoot "companies\$Name"
$envFile = Join-Path $companyDir ".env"
$traefikFile = Join-Path $composeRoot "infra\config\traefik\dynamic\company-$Name.yml"

New-Item -ItemType Directory -Force -Path $companyDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $companyDir "storage\assets") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $companyDir "storage\downloads") | Out-Null

$seedDemo = if ($DemoAssets) { "true" } else { "false" }
@"
COMPANY=$Name
SEED_DEMO_ASSETS=$seedDemo
"@ | Out-File -FilePath $envFile -Encoding ascii

@"
# Traefik routes for company '$Name' (generated by new-company.ps1)
http:
  routers:
    cp-${Name}:
      rule: "Host(``cp.$Name.localhost``)"
      entryPoints: [web]
      service: cp-$Name

    dp-${Name}:
      rule: "Host(``dp.$Name.localhost``) && PathPrefix(``/public``)"
      entryPoints: [web]
      middlewares: [strip-public-$Name]
      service: dp-$Name

    ih-cs-${Name}:
      rule: "Host(``ih.$Name.localhost``) && PathPrefix(``/cs``)"
      entryPoints: [web]
      middlewares: [strip-cs-$Name]
      service: ih-identity-$Name

    ih-did-${Name}:
      rule: "Host(``ih.$Name.localhost``)"
      entryPoints: [web]
      service: ih-did-$Name

  middlewares:
    strip-public-${Name}:
      stripPrefix:
        prefixes: ["/public"]
    strip-cs-${Name}:
      stripPrefix:
        prefixes: ["/cs"]

  services:
    cp-${Name}:
      loadBalancer:
        servers:
          - url: "http://controlplane-${Name}:8081"
    dp-${Name}:
      loadBalancer:
        servers:
          - url: "http://dataplane-${Name}:11002"
    ih-identity-${Name}:
      loadBalancer:
        servers:
          - url: "http://identityhub-${Name}:7081"
    ih-did-${Name}:
      loadBalancer:
        servers:
          - url: "http://identityhub-${Name}:7083"
"@ | Out-File -FilePath $traefikFile -Encoding ascii

Write-Host "Company '$Name' generated:"
Write-Host "  env file:      $envFile"
Write-Host "  traefik route: $traefikFile"

# Windows bind mounts do not deliver file-watch events into the container,
# so Traefik must be restarted to pick up the new route file.
podman restart traefik | Out-Null
Write-Host "  traefik restarted (route loaded)"

if (-not $NoDeploy) {
    Write-Host "Deploying stack mvd-$Name ..."
    podman compose -p "mvd-$Name" --env-file $envFile -f (Join-Path $composeRoot "company\docker-compose.yml") up -d
    Write-Host ""
    Write-Host "Company '$Name' deployed. Endpoints:"
    Write-Host "  Management API: http://cp.$Name.localhost/api/mgmt  (X-Api-Key: password)"
    Write-Host "  Dataplane:      http://dp.$Name.localhost/public"
    Write-Host "  DID:            did:web:identityhub-$Name%3A7083:$Name"
}
