// AM2Scale dataspace knowledge graph
// Sichtbarkeitsstufe: T1 (fremd)
// Erzeugt von ui/discovery/export_neo4j.py

// vorherigen Import entfernen
MATCH (n:KG) DETACH DELETE n;

// ===== fha-tirol  (Dataset: Fraunhofer Austria Tirol) =====
CREATE (:KG:Auftragsposition {id: 'position:A-002-1', owner: 'fha-tirol', kgType: 'Auftragsposition', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, materialnummer: 987654321, positionId: 'A-002-1', withheld: ['Auftragsmenge', 'Auftragsnummer', 'Position', 'Wunschlieferdatum']});
CREATE (:KG:Druckprofil {id: 'profil:987654321_FhA_Bambu', owner: 'fha-tirol', kgType: 'Druckprofil', tier: 1, sichtbar: 5, verborgen: 4, stufe: 1, materialnummer: 987654321, printerId: 'FhA_Bambu', werkstoff: 'TPU', profilId: '987654321_FhA_Bambu', druckerModell: 'BambuLAB_X1', withheld: ['Druckdauer (min)', 'G-Code', 'Menge pro Druck', 'Prüfstatus']});
CREATE (:KG:Auftragsposition {id: 'position:A-001-2', owner: 'fha-tirol', kgType: 'Auftragsposition', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, materialnummer: 987654321, positionId: 'A-001-2', withheld: ['Auftragsmenge', 'Auftragsnummer', 'Position', 'Wunschlieferdatum']});
CREATE (:KG:Auftragsposition {id: 'position:A-007-1', owner: 'fha-tirol', kgType: 'Auftragsposition', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, materialnummer: 987654321, positionId: 'A-007-1', withheld: ['Auftragsmenge', 'Auftragsnummer', 'Position', 'Wunschlieferdatum']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-011', owner: 'fha-tirol', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-011', materialnummer: 555111333, printerId: 'FhA_Ultimaker', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-012', owner: 'fha-tirol', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-012', materialnummer: 555111333, printerId: 'FhA_Ultimaker', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Unternehmen {id: 'unternehmen:U7', owner: 'fha-tirol', kgType: 'Unternehmen', tier: 1, sichtbar: 4, verborgen: 3, stufe: 1, uId: 'U7', name: 'Fraunhofer Austria Tirol', stadt: 'Innsbruck', land: 'Austria', withheld: ['CO₂ pro kWh', 'Straße', 'Stromtarif (€/kWh)']});
CREATE (:KG:Material {id: 'material:987654321', owner: 'fha-tirol', kgType: 'Material', tier: 1, sichtbar: 19, verborgen: 10, stufe: 1, materialnummer: 987654321, materialkurztext: 'PYC3D_DUCK_KEYCHAIN', werkstoff: 'ABS', normBezeichnung: 'EN 10088-3', laenge: 2.6, breite: 2.8, hoehe: 0.2, abmessungseinheit: 'CM', volumen: 1.179, nettogewicht: 0.04, bruttogewicht: 0.04, gewichtseinheit: 'KG', einsatzzweck: 'Schlüsselanhänger als Werbemittel und Giveaway, Nutzung im Alltag am Schlüsselbund', funktion: 'Trägt einen Schlüsselring, dient als Kennzeichnung und Blickfang', anforderungen: 'abriebfest, bruchsicher bei Sturz, kleine Bauform, leicht', branche: 'Marketing / Werbemittel', synonyme: 'Keychain, Anhänger, Schlüsselband, Ente, Duck', benennung: 'Enten-Schlüsselanhänger', edcAssetId: 'stammdaten-987654321', withheld: ['Bestandsmenge', 'Hersteller', 'Lieferant', 'Maximallosgröße', 'Mindestlosgröße', 'Planlieferzeit (Tage)', 'Preis', 'Sicherheitsbestand', 'Zeichnungsnummer (Hersteller)', 'interne Zeichnungsnummer']});
CREATE (:KG:Auftragsposition {id: 'position:A-003-1', owner: 'fha-tirol', kgType: 'Auftragsposition', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, materialnummer: 987654321, positionId: 'A-003-1', withheld: ['Auftragsmenge', 'Auftragsnummer', 'Position', 'Wunschlieferdatum']});
CREATE (:KG:Druckprofil {id: 'profil:987654321_FhA_Strata', owner: 'fha-tirol', kgType: 'Druckprofil', tier: 1, sichtbar: 5, verborgen: 4, stufe: 1, materialnummer: 987654321, printerId: 'FhA_Strata', werkstoff: 'TPU', profilId: '987654321_FhA_Strata', druckerModell: 'Stratasys_F170', withheld: ['Druckdauer (min)', 'G-Code', 'Menge pro Druck', 'Prüfstatus']});
CREATE (:KG:Drucker {id: 'drucker:FhA_Ultimaker', owner: 'fha-tirol', kgType: 'Drucker', tier: 1, sichtbar: 5, verborgen: 3, stufe: 1, printerId: 'FhA_Ultimaker', modell: 'Ultimaker_S5', druckbareWerkstoffe: 'PLA,ABS,PETG', standort: 'FhA_Graz', unternehmensId: 'U7', withheld: ['Geladene Werkstoffe', 'Prüfstatus', 'Seriennummer']});
CREATE (:KG:Auftragsposition {id: 'position:A-009-2', owner: 'fha-tirol', kgType: 'Auftragsposition', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, materialnummer: 987654321, positionId: 'A-009-2', withheld: ['Auftragsmenge', 'Auftragsnummer', 'Position', 'Wunschlieferdatum']});

MATCH (a:KG {id: 'unternehmen:U7', owner: 'fha-tirol'}), (b:KG {id: 'drucker:FhA_Ultimaker', owner: 'fha-tirol'}) CREATE (a)-[:BETREIBT]->(b);
MATCH (a:KG {id: 'unternehmen:U7', owner: 'fha-tirol'}), (b:KG {id: 'material:987654321', owner: 'fha-tirol'}) CREATE (a)-[:FUEHRT]->(b);
MATCH (a:KG {id: 'profil:987654321_FhA_Strata', owner: 'fha-tirol'}), (b:KG {id: 'material:987654321', owner: 'fha-tirol'}) CREATE (a)-[:FUER]->(b);
MATCH (a:KG {id: 'profil:987654321_FhA_Bambu', owner: 'fha-tirol'}), (b:KG {id: 'material:987654321', owner: 'fha-tirol'}) CREATE (a)-[:FUER]->(b);
MATCH (a:KG {id: 'position:A-001-2', owner: 'fha-tirol'}), (b:KG {id: 'material:987654321', owner: 'fha-tirol'}) CREATE (a)-[:BESTELLT]->(b);
MATCH (a:KG {id: 'position:A-002-1', owner: 'fha-tirol'}), (b:KG {id: 'material:987654321', owner: 'fha-tirol'}) CREATE (a)-[:BESTELLT]->(b);
MATCH (a:KG {id: 'position:A-003-1', owner: 'fha-tirol'}), (b:KG {id: 'material:987654321', owner: 'fha-tirol'}) CREATE (a)-[:BESTELLT]->(b);
MATCH (a:KG {id: 'position:A-007-1', owner: 'fha-tirol'}), (b:KG {id: 'material:987654321', owner: 'fha-tirol'}) CREATE (a)-[:BESTELLT]->(b);
MATCH (a:KG {id: 'position:A-009-2', owner: 'fha-tirol'}), (b:KG {id: 'material:987654321', owner: 'fha-tirol'}) CREATE (a)-[:BESTELLT]->(b);
MATCH (a:KG {id: 'fertigung:F-011', owner: 'fha-tirol'}), (b:KG {id: 'drucker:FhA_Ultimaker', owner: 'fha-tirol'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-012', owner: 'fha-tirol'}), (b:KG {id: 'drucker:FhA_Ultimaker', owner: 'fha-tirol'}) CREATE (a)-[:LAEUFT_AUF]->(b);

// ===== fha-wien  (Dataset: Fraunhofer Austria Wien) =====
CREATE (:KG:Bauteil {id: 'bauteil:A001-F001:123456789_B1', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B1', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Maschinendaten {id: 'serie:D12288:WORLDCUP_386_@VUP2W', owner: 'fha-wien', kgType: 'Maschinendaten', tier: 1, sichtbar: 2, verborgen: 5, stufe: 1, serieId: 'D12288:WORLDCUP_386_@VUP2W', printerId: 'FhA_Strata', withheld: ['Anzahl Messwerte', 'Job-Programm', 'Rohdaten-Referenz', 'Zeitraum bis', 'Zeitraum von']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-007', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-007', materialnummer: 555111222, printerId: 'FhA_Prusa', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Maschinendaten {id: 'serie:B12345:987654321_@IDQBN', owner: 'fha-wien', kgType: 'Maschinendaten', tier: 1, sichtbar: 2, verborgen: 5, stufe: 1, serieId: 'B12345:987654321_@IDQBN', printerId: 'FhA_Bambu', withheld: ['Anzahl Messwerte', 'Job-Programm', 'Rohdaten-Referenz', 'Zeitraum bis', 'Zeitraum von']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-004', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-004', materialnummer: 123456789, printerId: 'FhA_Bambu', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Bauteil {id: 'bauteil:A001-F001:123456789_B3', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B3', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Maschinendaten {id: 'serie:D12288:PYC3D_DUCK_KEYCHAIN_@N3OCR', owner: 'fha-wien', kgType: 'Maschinendaten', tier: 1, sichtbar: 2, verborgen: 5, stufe: 1, serieId: 'D12288:PYC3D_DUCK_KEYCHAIN_@N3OCR', printerId: 'FhA_Strata', withheld: ['Anzahl Messwerte', 'Job-Programm', 'Rohdaten-Referenz', 'Zeitraum bis', 'Zeitraum von']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-003', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-003', materialnummer: 123456789, printerId: 'FhA_Strata', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F007:555111222_B8', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '555111222_B8', materialnummer: 555111222, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A001-F001:123456789_B4', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B4', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-016', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-016', materialnummer: 987654321, printerId: 'FhA_Strata', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-023', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-023', materialnummer: 123456789, printerId: 'FhA_Prusa', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Maschinendaten {id: 'serie:D12288:WORLDCUP_386_@XRWGL', owner: 'fha-wien', kgType: 'Maschinendaten', tier: 1, sichtbar: 2, verborgen: 5, stufe: 1, serieId: 'D12288:WORLDCUP_386_@XRWGL', printerId: 'FhA_Strata', withheld: ['Anzahl Messwerte', 'Job-Programm', 'Rohdaten-Referenz', 'Zeitraum bis', 'Zeitraum von']});
CREATE (:KG:Bauteil {id: 'bauteil:A001-F001:123456789_B10', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B10', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A003-F005:987654321_B8', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '987654321_B8', materialnummer: 987654321, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-006', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-006', materialnummer: 987654321, printerId: 'FhA_Bambu', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Bauteil {id: 'bauteil:A001-F001:123456789_B6', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B6', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Auftragsposition {id: 'position:A-010-1', owner: 'fha-wien', kgType: 'Auftragsposition', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, materialnummer: 123456789, positionId: 'A-010-1', withheld: ['Auftragsmenge', 'Auftragsnummer', 'Position', 'Wunschlieferdatum']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-013', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-013', materialnummer: 123456789, printerId: 'FhA_Bambu', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F007:555111222_B5', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '555111222_B5', materialnummer: 555111222, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Drucker {id: 'drucker:FhA_Bambu', owner: 'fha-wien', kgType: 'Drucker', tier: 1, sichtbar: 5, verborgen: 3, stufe: 1, printerId: 'FhA_Bambu', modell: 'BambuLAB_X1', druckbareWerkstoffe: 'ABS,TPU,PETG', standort: 'FhA_Wien', unternehmensId: 'U6', withheld: ['Geladene Werkstoffe', 'Prüfstatus', 'Seriennummer']});
CREATE (:KG:Maschinendaten {id: 'serie:D12288:PYC3D_DUCK_KEYCHAIN_@F7LLC', owner: 'fha-wien', kgType: 'Maschinendaten', tier: 1, sichtbar: 2, verborgen: 5, stufe: 1, serieId: 'D12288:PYC3D_DUCK_KEYCHAIN_@F7LLC', printerId: 'FhA_Strata', withheld: ['Anzahl Messwerte', 'Job-Programm', 'Rohdaten-Referenz', 'Zeitraum bis', 'Zeitraum von']});
CREATE (:KG:Bauteil {id: 'bauteil:A001-F001:123456789_B2', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B2', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A001-F001:123456789_B8', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B8', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F009:123456789_B9', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B9', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A001-F001:123456789_B5', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B5', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-019', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-019', materialnummer: 555111333, printerId: 'FhA_Bambu', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Qualitaetspruefung {id: 'qs:QS-A004-F007', owner: 'fha-wien', kgType: 'Qualitaetspruefung', tier: 1, sichtbar: 2, verborgen: 6, stufe: 1, materialnummer: 555111222, pruefungId: 'QS-A004-F007', withheld: ['3D-Scan', 'Abweichung X', 'Abweichung Y', 'Abweichung Z', 'Charge', 'Prüfstatus']});
CREATE (:KG:Bauteil {id: 'bauteil:A001-F001:123456789_B9', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B9', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F007:555111222_B6', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '555111222_B6', materialnummer: 555111222, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Qualitaetspruefung {id: 'qs:QS-A001-F001', owner: 'fha-wien', kgType: 'Qualitaetspruefung', tier: 1, sichtbar: 2, verborgen: 6, stufe: 1, materialnummer: 123456789, pruefungId: 'QS-A001-F001', withheld: ['3D-Scan', 'Abweichung X', 'Abweichung Y', 'Abweichung Z', 'Charge', 'Prüfstatus']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F007:555111222_B9', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '555111222_B9', materialnummer: 555111222, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Druckprofil {id: 'profil:123456789_FhA_Bambu', owner: 'fha-wien', kgType: 'Druckprofil', tier: 1, sichtbar: 5, verborgen: 4, stufe: 1, materialnummer: 123456789, printerId: 'FhA_Bambu', werkstoff: 'ABS', profilId: '123456789_FhA_Bambu', druckerModell: 'BambuLAB_X1', withheld: ['Druckdauer (min)', 'G-Code', 'Menge pro Druck', 'Prüfstatus']});
CREATE (:KG:Bauteil {id: 'bauteil:A003-F005:987654321_B7', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '987654321_B7', materialnummer: 987654321, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F009:123456789_B8', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B8', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-018', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-018', materialnummer: 555111222, printerId: 'FhA_Strata', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Unternehmen {id: 'unternehmen:U6', owner: 'fha-wien', kgType: 'Unternehmen', tier: 1, sichtbar: 4, verborgen: 3, stufe: 1, uId: 'U6', name: 'Fraunhofer Austria Wien', stadt: 'Wien', land: 'Austria', withheld: ['CO₂ pro kWh', 'Straße', 'Stromtarif (€/kWh)']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-008', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-008', materialnummer: 555111222, printerId: 'FhA_Prusa', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Druckprofil {id: 'profil:123456789_FhA_Strata', owner: 'fha-wien', kgType: 'Druckprofil', tier: 1, sichtbar: 5, verborgen: 4, stufe: 1, materialnummer: 123456789, printerId: 'FhA_Strata', werkstoff: 'ABS', profilId: '123456789_FhA_Strata', druckerModell: 'Stratasys_F170', withheld: ['Druckdauer (min)', 'G-Code', 'Menge pro Druck', 'Prüfstatus']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F007:555111222_B4', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '555111222_B4', materialnummer: 555111222, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F009:123456789_B10', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B10', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F007:555111222_B1', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '555111222_B1', materialnummer: 555111222, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-014', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-014', materialnummer: 123456789, printerId: 'FhA_Bambu', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-005', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-005', materialnummer: 987654321, printerId: 'FhA_Bambu', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Bauteil {id: 'bauteil:A003-F005:987654321_B5', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '987654321_B5', materialnummer: 987654321, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F009:123456789_B1', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B1', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-015', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-015', materialnummer: 987654321, printerId: 'FhA_Strata', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Auftragsposition {id: 'position:A-004-2', owner: 'fha-wien', kgType: 'Auftragsposition', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, materialnummer: 123456789, positionId: 'A-004-2', withheld: ['Auftragsmenge', 'Auftragsnummer', 'Position', 'Wunschlieferdatum']});
CREATE (:KG:Bauteil {id: 'bauteil:A001-F001:123456789_B7', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B7', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Qualitaetspruefung {id: 'qs:QS-A004-F009', owner: 'fha-wien', kgType: 'Qualitaetspruefung', tier: 1, sichtbar: 2, verborgen: 6, stufe: 1, materialnummer: 123456789, pruefungId: 'QS-A004-F009', withheld: ['3D-Scan', 'Abweichung X', 'Abweichung Y', 'Abweichung Z', 'Charge', 'Prüfstatus']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-022', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-022', materialnummer: 987654321, printerId: 'FhA_Bambu', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-009', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-009', materialnummer: 123456789, printerId: 'FhA_Strata', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Bauteil {id: 'bauteil:A003-F005:987654321_B6', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '987654321_B6', materialnummer: 987654321, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Maschinendaten {id: 'serie:P99001:555111222_@VHGPI', owner: 'fha-wien', kgType: 'Maschinendaten', tier: 1, sichtbar: 2, verborgen: 5, stufe: 1, serieId: 'P99001:555111222_@VHGPI', printerId: 'FhA_Prusa', withheld: ['Anzahl Messwerte', 'Job-Programm', 'Rohdaten-Referenz', 'Zeitraum bis', 'Zeitraum von']});
CREATE (:KG:Auftragsposition {id: 'position:A-006-1', owner: 'fha-wien', kgType: 'Auftragsposition', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, materialnummer: 123456789, positionId: 'A-006-1', withheld: ['Auftragsmenge', 'Auftragsnummer', 'Position', 'Wunschlieferdatum']});
CREATE (:KG:Bauteil {id: 'bauteil:A003-F005:987654321_B1', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '987654321_B1', materialnummer: 987654321, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A003-F005:987654321_B10', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '987654321_B10', materialnummer: 987654321, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A003-F005:987654321_B2', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '987654321_B2', materialnummer: 987654321, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F007:555111222_B3', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '555111222_B3', materialnummer: 555111222, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A003-F005:987654321_B4', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '987654321_B4', materialnummer: 987654321, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A003-F005:987654321_B9', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '987654321_B9', materialnummer: 987654321, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A003-F005:987654321_B3', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '987654321_B3', materialnummer: 987654321, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F009:123456789_B5', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B5', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Qualitaetspruefung {id: 'qs:QS-A003-F005', owner: 'fha-wien', kgType: 'Qualitaetspruefung', tier: 1, sichtbar: 2, verborgen: 6, stufe: 1, materialnummer: 987654321, pruefungId: 'QS-A003-F005', withheld: ['3D-Scan', 'Abweichung X', 'Abweichung Y', 'Abweichung Z', 'Charge', 'Prüfstatus']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-010', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-010', materialnummer: 123456789, printerId: 'FhA_Strata', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Druckprofil {id: 'profil:123456789_FhA_Prusa', owner: 'fha-wien', kgType: 'Druckprofil', tier: 1, sichtbar: 5, verborgen: 4, stufe: 1, materialnummer: 123456789, printerId: 'FhA_Prusa', werkstoff: 'ABS', profilId: '123456789_FhA_Prusa', druckerModell: 'Prusa_MK4S', withheld: ['Druckdauer (min)', 'G-Code', 'Menge pro Druck', 'Prüfstatus']});
CREATE (:KG:Drucker {id: 'drucker:FhA_Strata', owner: 'fha-wien', kgType: 'Drucker', tier: 1, sichtbar: 5, verborgen: 3, stufe: 1, printerId: 'FhA_Strata', modell: 'Stratasys_F170', druckbareWerkstoffe: 'ABS,PLA,PETG,Support, TPU', standort: 'FhA_Wien', unternehmensId: 'U6', withheld: ['Geladene Werkstoffe', 'Prüfstatus', 'Seriennummer']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F009:123456789_B3', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B3', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Material {id: 'material:123456789', owner: 'fha-wien', kgType: 'Material', tier: 1, sichtbar: 19, verborgen: 10, stufe: 1, materialnummer: 123456789, materialkurztext: 'Worldcup_386', werkstoff: 'ABS', normBezeichnung: 'EN 10088-3', laenge: 1.4, breite: 1.5, hoehe: 3.7, abmessungseinheit: 'CM', volumen: 4.188, nettogewicht: 0.12, bruttogewicht: 0.12, gewichtseinheit: 'KG', einsatzzweck: 'Werbe- und Repräsentationsartikel für Messen und Veranstaltungen, Aufstellung in Innenräumen', funktion: 'Dekoratives Standobjekt in Pokalform, freistehend auf ebener Fläche', anforderungen: 'formstabil bei Raumtemperatur, schlagzäh, oberflächenbehandelbar (lackierbar)', branche: 'Marketing / Veranstaltungstechnik', synonyme: 'Pokal, Trophäe, Cup, Siegerpokal, Auszeichnung', benennung: 'Pokal', edcAssetId: 'stammdaten-123456789', withheld: ['Bestandsmenge', 'Hersteller', 'Lieferant', 'Maximallosgröße', 'Mindestlosgröße', 'Planlieferzeit (Tage)', 'Preis', 'Sicherheitsbestand', 'Zeichnungsnummer (Hersteller)', 'interne Zeichnungsnummer']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F009:123456789_B7', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B7', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F009:123456789_B2', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B2', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F007:555111222_B10', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '555111222_B10', materialnummer: 555111222, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F007:555111222_B11', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '555111222_B11', materialnummer: 555111222, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Maschinendaten {id: 'serie:D12288:WORLDCUP_386_@HWSAX', owner: 'fha-wien', kgType: 'Maschinendaten', tier: 1, sichtbar: 2, verborgen: 5, stufe: 1, serieId: 'D12288:WORLDCUP_386_@HWSAX', printerId: 'FhA_Strata', withheld: ['Anzahl Messwerte', 'Job-Programm', 'Rohdaten-Referenz', 'Zeitraum bis', 'Zeitraum von']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F007:555111222_B12', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '555111222_B12', materialnummer: 555111222, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-002', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-002', materialnummer: 123456789, printerId: 'FhA_Strata', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F009:123456789_B4', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B4', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-001', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-001', materialnummer: 123456789, printerId: 'FhA_Strata', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-020', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-020', materialnummer: 555111333, printerId: 'FhA_Bambu', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F007:555111222_B2', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '555111222_B2', materialnummer: 555111222, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Auftragsposition {id: 'position:A-001-1', owner: 'fha-wien', kgType: 'Auftragsposition', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, materialnummer: 123456789, positionId: 'A-001-1', withheld: ['Auftragsmenge', 'Auftragsnummer', 'Position', 'Wunschlieferdatum']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F009:123456789_B6', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '123456789_B6', materialnummer: 123456789, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-021', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-021', materialnummer: 555111333, printerId: 'FhA_Bambu', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});
CREATE (:KG:Drucker {id: 'drucker:FhA_Prusa', owner: 'fha-wien', kgType: 'Drucker', tier: 1, sichtbar: 5, verborgen: 3, stufe: 1, printerId: 'FhA_Prusa', modell: 'Prusa_MK4S', druckbareWerkstoffe: 'PLA,PETG,TPU,ABS', standort: 'FhA_Wien', unternehmensId: 'U6', withheld: ['Geladene Werkstoffe', 'Prüfstatus', 'Seriennummer']});
CREATE (:KG:Bauteil {id: 'bauteil:A004-F007:555111222_B7', owner: 'fha-wien', kgType: 'Bauteil', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, bauteilId: '555111222_B7', materialnummer: 555111222, withheld: ['Charge', 'DPP-Ereignisse', 'DPP-Status', 'DPP-Version']});
CREATE (:KG:Fertigungsauftrag {id: 'fertigung:F-017', owner: 'fha-wien', kgType: 'Fertigungsauftrag', tier: 1, sichtbar: 3, verborgen: 7, stufe: 1, fertigungsauftragId: 'F-017', materialnummer: 555111222, printerId: 'FhA_Strata', withheld: ['Auftragsnummer', 'Charge', 'Dauer (min)', 'Endzeitpunkt', 'Menge', 'Position', 'Startzeitpunkt']});

MATCH (a:KG {id: 'unternehmen:U6', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}) CREATE (a)-[:BETREIBT]->(b);
MATCH (a:KG {id: 'unternehmen:U6', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Bambu', owner: 'fha-wien'}) CREATE (a)-[:BETREIBT]->(b);
MATCH (a:KG {id: 'unternehmen:U6', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Prusa', owner: 'fha-wien'}) CREATE (a)-[:BETREIBT]->(b);
MATCH (a:KG {id: 'unternehmen:U6', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:FUEHRT]->(b);
MATCH (a:KG {id: 'profil:123456789_FhA_Strata', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:FUER]->(b);
MATCH (a:KG {id: 'profil:123456789_FhA_Strata', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'profil:123456789_FhA_Bambu', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:FUER]->(b);
MATCH (a:KG {id: 'profil:123456789_FhA_Bambu', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Bambu', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'profil:123456789_FhA_Prusa', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:FUER]->(b);
MATCH (a:KG {id: 'profil:123456789_FhA_Prusa', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Prusa', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'position:A-001-1', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:BESTELLT]->(b);
MATCH (a:KG {id: 'position:A-004-2', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:BESTELLT]->(b);
MATCH (a:KG {id: 'position:A-006-1', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:BESTELLT]->(b);
MATCH (a:KG {id: 'position:A-010-1', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:BESTELLT]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:FERTIGT]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'position:A-001-1', owner: 'fha-wien'}) CREATE (a)-[:ERFUELLT]->(b);
MATCH (a:KG {id: 'fertigung:F-002', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-002', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:FERTIGT]->(b);
MATCH (a:KG {id: 'fertigung:F-002', owner: 'fha-wien'}), (b:KG {id: 'position:A-001-1', owner: 'fha-wien'}) CREATE (a)-[:ERFUELLT]->(b);
MATCH (a:KG {id: 'fertigung:F-003', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-003', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:FERTIGT]->(b);
MATCH (a:KG {id: 'fertigung:F-003', owner: 'fha-wien'}), (b:KG {id: 'position:A-001-1', owner: 'fha-wien'}) CREATE (a)-[:ERFUELLT]->(b);
MATCH (a:KG {id: 'fertigung:F-004', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Bambu', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-004', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:FERTIGT]->(b);
MATCH (a:KG {id: 'fertigung:F-004', owner: 'fha-wien'}), (b:KG {id: 'position:A-001-1', owner: 'fha-wien'}) CREATE (a)-[:ERFUELLT]->(b);
MATCH (a:KG {id: 'fertigung:F-005', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Bambu', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-006', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Bambu', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Prusa', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-008', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Prusa', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:FERTIGT]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'position:A-004-2', owner: 'fha-wien'}) CREATE (a)-[:ERFUELLT]->(b);
MATCH (a:KG {id: 'fertigung:F-010', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-010', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:FERTIGT]->(b);
MATCH (a:KG {id: 'fertigung:F-010', owner: 'fha-wien'}), (b:KG {id: 'position:A-004-2', owner: 'fha-wien'}) CREATE (a)-[:ERFUELLT]->(b);
MATCH (a:KG {id: 'fertigung:F-013', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Bambu', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-013', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:FERTIGT]->(b);
MATCH (a:KG {id: 'fertigung:F-013', owner: 'fha-wien'}), (b:KG {id: 'position:A-006-1', owner: 'fha-wien'}) CREATE (a)-[:ERFUELLT]->(b);
MATCH (a:KG {id: 'fertigung:F-014', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Bambu', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-014', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:FERTIGT]->(b);
MATCH (a:KG {id: 'fertigung:F-014', owner: 'fha-wien'}), (b:KG {id: 'position:A-006-1', owner: 'fha-wien'}) CREATE (a)-[:ERFUELLT]->(b);
MATCH (a:KG {id: 'fertigung:F-015', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-016', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-017', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-018', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-019', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Bambu', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-020', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Bambu', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-021', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Bambu', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-022', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Bambu', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-023', owner: 'fha-wien'}), (b:KG {id: 'drucker:FhA_Prusa', owner: 'fha-wien'}) CREATE (a)-[:LAEUFT_AUF]->(b);
MATCH (a:KG {id: 'fertigung:F-023', owner: 'fha-wien'}), (b:KG {id: 'material:123456789', owner: 'fha-wien'}) CREATE (a)-[:FERTIGT]->(b);
MATCH (a:KG {id: 'fertigung:F-023', owner: 'fha-wien'}), (b:KG {id: 'position:A-010-1', owner: 'fha-wien'}) CREATE (a)-[:ERFUELLT]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A001-F001:123456789_B1', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A001-F001:123456789_B2', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A001-F001:123456789_B3', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A001-F001:123456789_B4', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A001-F001:123456789_B5', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A001-F001:123456789_B6', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A001-F001:123456789_B7', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A001-F001:123456789_B8', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A001-F001:123456789_B9', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A001-F001:123456789_B10', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-005', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A003-F005:987654321_B1', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-005', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A003-F005:987654321_B2', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-005', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A003-F005:987654321_B3', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-005', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A003-F005:987654321_B4', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-005', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A003-F005:987654321_B5', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-005', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A003-F005:987654321_B6', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-005', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A003-F005:987654321_B7', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-005', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A003-F005:987654321_B8', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-005', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A003-F005:987654321_B9', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-005', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A003-F005:987654321_B10', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F007:555111222_B1', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F007:555111222_B2', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F007:555111222_B3', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F007:555111222_B4', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F007:555111222_B5', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F007:555111222_B6', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F007:555111222_B7', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F007:555111222_B8', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F007:555111222_B9', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F007:555111222_B10', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F007:555111222_B11', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F007:555111222_B12', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F009:123456789_B1', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F009:123456789_B2', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F009:123456789_B3', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F009:123456789_B4', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F009:123456789_B5', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F009:123456789_B6', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F009:123456789_B7', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F009:123456789_B8', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F009:123456789_B9', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'bauteil:A004-F009:123456789_B10', owner: 'fha-wien'}) CREATE (a)-[:ERZEUGT]->(b);
MATCH (a:KG {id: 'fertigung:F-001', owner: 'fha-wien'}), (b:KG {id: 'qs:QS-A001-F001', owner: 'fha-wien'}) CREATE (a)-[:GEPRUEFT_IN]->(b);
MATCH (a:KG {id: 'fertigung:F-005', owner: 'fha-wien'}), (b:KG {id: 'qs:QS-A003-F005', owner: 'fha-wien'}) CREATE (a)-[:GEPRUEFT_IN]->(b);
MATCH (a:KG {id: 'fertigung:F-007', owner: 'fha-wien'}), (b:KG {id: 'qs:QS-A004-F007', owner: 'fha-wien'}) CREATE (a)-[:GEPRUEFT_IN]->(b);
MATCH (a:KG {id: 'fertigung:F-009', owner: 'fha-wien'}), (b:KG {id: 'qs:QS-A004-F009', owner: 'fha-wien'}) CREATE (a)-[:GEPRUEFT_IN]->(b);
MATCH (a:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}), (b:KG {id: 'serie:D12288:WORLDCUP_386_@VUP2W', owner: 'fha-wien'}) CREATE (a)-[:LIEFERT]->(b);
MATCH (a:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}), (b:KG {id: 'serie:D12288:WORLDCUP_386_@HWSAX', owner: 'fha-wien'}) CREATE (a)-[:LIEFERT]->(b);
MATCH (a:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}), (b:KG {id: 'serie:D12288:WORLDCUP_386_@XRWGL', owner: 'fha-wien'}) CREATE (a)-[:LIEFERT]->(b);
MATCH (a:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}), (b:KG {id: 'serie:D12288:PYC3D_DUCK_KEYCHAIN_@N3OCR', owner: 'fha-wien'}) CREATE (a)-[:LIEFERT]->(b);
MATCH (a:KG {id: 'drucker:FhA_Strata', owner: 'fha-wien'}), (b:KG {id: 'serie:D12288:PYC3D_DUCK_KEYCHAIN_@F7LLC', owner: 'fha-wien'}) CREATE (a)-[:LIEFERT]->(b);
MATCH (a:KG {id: 'drucker:FhA_Bambu', owner: 'fha-wien'}), (b:KG {id: 'serie:B12345:987654321_@IDQBN', owner: 'fha-wien'}) CREATE (a)-[:LIEFERT]->(b);
MATCH (a:KG {id: 'drucker:FhA_Prusa', owner: 'fha-wien'}), (b:KG {id: 'serie:P99001:555111222_@VHGPI', owner: 'fha-wien'}) CREATE (a)-[:LIEFERT]->(b);

// ===== oebb  (Dataset: ÖBB) =====
CREATE (:KG:Unternehmen {id: 'unternehmen:U1', owner: 'oebb', kgType: 'Unternehmen', tier: 1, sichtbar: 4, verborgen: 3, stufe: 1, uId: 'U1', name: 'ÖBB', stadt: 'Wien', land: 'Austria', withheld: ['CO₂ pro kWh', 'Straße', 'Stromtarif (€/kWh)']});
CREATE (:KG:Material {id: 'material:555111222', owner: 'oebb', kgType: 'Material', tier: 1, sichtbar: 19, verborgen: 10, stufe: 1, materialnummer: 555111222, materialkurztext: 'Adapterplatte_47', werkstoff: 'PLA', normBezeichnung: 'EN 10088-3', laenge: 5, breite: 4, hoehe: 1.2, abmessungseinheit: 'CM', volumen: 2.5, nettogewicht: 0.08, bruttogewicht: 0.08, gewichtseinheit: 'KG', einsatzzweck: 'Montageadapter zur Befestigung von Geräten auf abweichenden Lochbildern, Einsatz im Schaltschrank und an Montageplatten', funktion: 'Überbrückt unterschiedliche Bohrbilder, nimmt Schraubverbindungen auf und verteilt die Last flächig', anforderungen: 'maßhaltig, formstabil unter Schraubvorspannung, elektrisch isolierend', branche: 'Elektrotechnik / Maschinenbau', synonyme: 'Adapterplatte, Montageplatte, Zwischenplatte, Befestigungsadapter, Lochbildadapter', benennung: 'Adapterplatte', edcAssetId: 'stammdaten-555111222', withheld: ['Bestandsmenge', 'Hersteller', 'Lieferant', 'Maximallosgröße', 'Mindestlosgröße', 'Planlieferzeit (Tage)', 'Preis', 'Sicherheitsbestand', 'Zeichnungsnummer (Hersteller)', 'interne Zeichnungsnummer']});
CREATE (:KG:Druckprofil {id: 'profil:555111222_FhA_Strata', owner: 'oebb', kgType: 'Druckprofil', tier: 1, sichtbar: 5, verborgen: 4, stufe: 1, materialnummer: 555111222, printerId: 'FhA_Strata', werkstoff: 'PLA', profilId: '555111222_FhA_Strata', druckerModell: 'Stratasys_F170', withheld: ['Druckdauer (min)', 'G-Code', 'Menge pro Druck', 'Prüfstatus']});
CREATE (:KG:Auftragsposition {id: 'position:A-008-1', owner: 'oebb', kgType: 'Auftragsposition', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, materialnummer: 555111222, positionId: 'A-008-1', withheld: ['Auftragsmenge', 'Auftragsnummer', 'Position', 'Wunschlieferdatum']});
CREATE (:KG:Auftragsposition {id: 'position:A-004-1', owner: 'oebb', kgType: 'Auftragsposition', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, materialnummer: 555111222, positionId: 'A-004-1', withheld: ['Auftragsmenge', 'Auftragsnummer', 'Position', 'Wunschlieferdatum']});
CREATE (:KG:Druckprofil {id: 'profil:555111222_FhA_Prusa', owner: 'oebb', kgType: 'Druckprofil', tier: 1, sichtbar: 5, verborgen: 4, stufe: 1, materialnummer: 555111222, printerId: 'FhA_Prusa', werkstoff: 'PLA', profilId: '555111222_FhA_Prusa', druckerModell: 'Prusa_MK4S', withheld: ['Druckdauer (min)', 'G-Code', 'Menge pro Druck', 'Prüfstatus']});

MATCH (a:KG {id: 'unternehmen:U1', owner: 'oebb'}), (b:KG {id: 'material:555111222', owner: 'oebb'}) CREATE (a)-[:FUEHRT]->(b);
MATCH (a:KG {id: 'profil:555111222_FhA_Strata', owner: 'oebb'}), (b:KG {id: 'material:555111222', owner: 'oebb'}) CREATE (a)-[:FUER]->(b);
MATCH (a:KG {id: 'profil:555111222_FhA_Prusa', owner: 'oebb'}), (b:KG {id: 'material:555111222', owner: 'oebb'}) CREATE (a)-[:FUER]->(b);
MATCH (a:KG {id: 'position:A-004-1', owner: 'oebb'}), (b:KG {id: 'material:555111222', owner: 'oebb'}) CREATE (a)-[:BESTELLT]->(b);
MATCH (a:KG {id: 'position:A-008-1', owner: 'oebb'}), (b:KG {id: 'material:555111222', owner: 'oebb'}) CREATE (a)-[:BESTELLT]->(b);

// ===== wien-energie  (Dataset: WienEnergie) =====
CREATE (:KG:Unternehmen {id: 'unternehmen:U3', owner: 'wien-energie', kgType: 'Unternehmen', tier: 1, sichtbar: 4, verborgen: 3, stufe: 1, uId: 'U3', name: 'WienEnergie', stadt: 'Wien', land: 'Austria', withheld: ['CO₂ pro kWh', 'Straße', 'Stromtarif (€/kWh)']});


// ===== wiener-linien  (Dataset: WienerLinien) =====
CREATE (:KG:Material {id: 'material:555111333', owner: 'wiener-linien', kgType: 'Material', tier: 1, sichtbar: 19, verborgen: 10, stufe: 1, materialnummer: 555111333, materialkurztext: 'Gehaeusedeckel_Klein', werkstoff: 'PETG', normBezeichnung: 'EN 10088-3', laenge: 6, breite: 6, hoehe: 1.8, abmessungseinheit: 'CM', volumen: 5.9, nettogewicht: 0.15, bruttogewicht: 0.15, gewichtseinheit: 'KG', einsatzzweck: 'Abdeckung für Kleingehäuse in Elektroinstallationen, Schutz von Klemmen und Platinen vor Staub und Berührung', funktion: 'Verschließt das Gehäuse formschlüssig, schützt Innenleben, ermöglicht Zugang bei Wartung', anforderungen: 'schlagzäh, temperaturbeständig, chemikalienbeständig, gute Maßhaltigkeit für Passung', branche: 'Elektrotechnik / Gehäusebau', synonyme: 'Gehäusedeckel, Abdeckung, Deckel, Gehäuseabdeckung, Schutzdeckel', benennung: 'Gehäusedeckel klein', edcAssetId: 'stammdaten-555111333', withheld: ['Bestandsmenge', 'Hersteller', 'Lieferant', 'Maximallosgröße', 'Mindestlosgröße', 'Planlieferzeit (Tage)', 'Preis', 'Sicherheitsbestand', 'Zeichnungsnummer (Hersteller)', 'interne Zeichnungsnummer']});
CREATE (:KG:Druckprofil {id: 'profil:555111333_FhA_Bambu', owner: 'wiener-linien', kgType: 'Druckprofil', tier: 1, sichtbar: 5, verborgen: 4, stufe: 1, materialnummer: 555111333, printerId: 'FhA_Bambu', werkstoff: 'PETG', profilId: '555111333_FhA_Bambu', druckerModell: 'BambuLAB_X1', withheld: ['Druckdauer (min)', 'G-Code', 'Menge pro Druck', 'Prüfstatus']});
CREATE (:KG:Unternehmen {id: 'unternehmen:U2', owner: 'wiener-linien', kgType: 'Unternehmen', tier: 1, sichtbar: 4, verborgen: 3, stufe: 1, uId: 'U2', name: 'WienerLinien', stadt: 'Wien', land: 'Austria', withheld: ['CO₂ pro kWh', 'Straße', 'Stromtarif (€/kWh)']});
CREATE (:KG:Druckprofil {id: 'profil:555111333_FhA_Ultimaker', owner: 'wiener-linien', kgType: 'Druckprofil', tier: 1, sichtbar: 5, verborgen: 4, stufe: 1, materialnummer: 555111333, printerId: 'FhA_Ultimaker', werkstoff: 'PETG', profilId: '555111333_FhA_Ultimaker', druckerModell: 'Ultimaker_S5', withheld: ['Druckdauer (min)', 'G-Code', 'Menge pro Druck', 'Prüfstatus']});
CREATE (:KG:Auftragsposition {id: 'position:A-009-1', owner: 'wiener-linien', kgType: 'Auftragsposition', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, materialnummer: 555111333, positionId: 'A-009-1', withheld: ['Auftragsmenge', 'Auftragsnummer', 'Position', 'Wunschlieferdatum']});
CREATE (:KG:Auftragsposition {id: 'position:A-005-1', owner: 'wiener-linien', kgType: 'Auftragsposition', tier: 1, sichtbar: 2, verborgen: 4, stufe: 1, materialnummer: 555111333, positionId: 'A-005-1', withheld: ['Auftragsmenge', 'Auftragsnummer', 'Position', 'Wunschlieferdatum']});

MATCH (a:KG {id: 'unternehmen:U2', owner: 'wiener-linien'}), (b:KG {id: 'material:555111333', owner: 'wiener-linien'}) CREATE (a)-[:FUEHRT]->(b);
MATCH (a:KG {id: 'profil:555111333_FhA_Bambu', owner: 'wiener-linien'}), (b:KG {id: 'material:555111333', owner: 'wiener-linien'}) CREATE (a)-[:FUER]->(b);
MATCH (a:KG {id: 'profil:555111333_FhA_Ultimaker', owner: 'wiener-linien'}), (b:KG {id: 'material:555111333', owner: 'wiener-linien'}) CREATE (a)-[:FUER]->(b);
MATCH (a:KG {id: 'position:A-005-1', owner: 'wiener-linien'}), (b:KG {id: 'material:555111333', owner: 'wiener-linien'}) CREATE (a)-[:BESTELLT]->(b);
MATCH (a:KG {id: 'position:A-009-1', owner: 'wiener-linien'}), (b:KG {id: 'material:555111333', owner: 'wiener-linien'}) CREATE (a)-[:BESTELLT]->(b);

// ===== wiener-netze  (Dataset: WienerNetze) =====
CREATE (:KG:Unternehmen {id: 'unternehmen:U4', owner: 'wiener-netze', kgType: 'Unternehmen', tier: 1, sichtbar: 4, verborgen: 3, stufe: 1, uId: 'U4', name: 'WienerNetze', stadt: 'Wien', land: 'Austria', withheld: ['CO₂ pro kWh', 'Straße', 'Stromtarif (€/kWh)']});


// ===== wiener-stadtwerke  (Dataset: Wiener Stadtwerke) =====
CREATE (:KG:Unternehmen {id: 'unternehmen:U0', owner: 'wiener-stadtwerke', kgType: 'Unternehmen', tier: 1, sichtbar: 4, verborgen: 3, stufe: 1, uId: 'U0', name: 'Wiener Stadtwerke', stadt: 'Wien', land: 'Austria', withheld: ['CO₂ pro kWh', 'Straße', 'Stromtarif (€/kWh)']});


// ---- nützliche Abfragen (im Neo4j Browser einzeln ausführen) ----
// alles anzeigen:            MATCH (n:KG)-[r]->(m:KG) RETURN n, r, m;
// ein Unternehmen:           MATCH (n:KG {owner:'fha-wien'})-[r]->(m) RETURN n,r,m;
// Bauteile mit Werkstoff:    MATCH (b:Bauteil) RETURN b.owner, b.benennung, b.werkstoff, b.abmessung;
// Herkunftskette eines DPP:  MATCH p=(d:DPP)-[*1..3]-(x:KG) RETURN p;
// was verbirgt dieses Level: MATCH (n:KG) WHERE n.verborgen > 0 RETURN n.owner, n.kgType, n.sichtbar, n.verborgen, n.withheld ORDER BY n.verborgen DESC;
